# Generated by Django 5.1.5 on 2025-05-22 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Givas',
            fields=[
                ('idgiva', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_giva', models.CharField(max_length=30, verbose_name='Descripción')),
                ('valoriva', models.IntegerField(verbose_name='Valor Iva')),
            ],
            options={
                'verbose_name': 'Graba Iva',
                'verbose_name_plural': 'Graba Ivas',
                'db_table': 'givas',
            },
        ),
        migrations.CreateModel(
            name='NivelesAzucar',
            fields=[
                ('idnivelazucar', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_nazucar', models.CharField(max_length=50, verbose_name='Descripción')),
                ('valor_nivel', models.IntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Nivel de Azúcar',
                'verbose_name_plural': 'Niveles de Azúcar',
                'db_table': 'niveles_azucar',
            },
        ),
        migrations.CreateModel(
            name='NivelesGrasa',
            fields=[
                ('idnivelgrasa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_ngrasa', models.CharField(max_length=50, verbose_name='Descripción')),
                ('valor_nivel', models.IntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Nivel de Grasa',
                'verbose_name_plural': 'Niveles de Grasa',
                'db_table': 'niveles_grasa',
            },
        ),
        migrations.CreateModel(
            name='NivelesSal',
            fields=[
                ('idnivelsal', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_nsal', models.CharField(max_length=50, verbose_name='Descripción')),
                ('valor_nivel', models.IntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Nivel de Sal',
                'verbose_name_plural': 'Niveles de Sal',
                'db_table': 'niveles_sal',
            },
        ),
        migrations.CreateModel(
            name='TipoArticulos',
            fields=[
                ('idtipoarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tipo', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo Artículo',
                'verbose_name_plural': 'Tipos Artículos',
                'db_table': 'tipos_articulos',
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('codigoarticulo', models.CharField(max_length=10, unique=True, verbose_name='Código de Producto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('descripcion_articulo', models.CharField(max_length=100, verbose_name='Descripción')),
                ('tiene_semaforo', models.BooleanField(default=False, verbose_name='¿Tiene semáforo?')),
                ('tiene_fecha_caduca', models.BooleanField(default=False, verbose_name='¿Tiene fecha de caducidad?')),
                ('manejo_por_lotes', models.BooleanField(default=False, verbose_name='¿Se maneja por lotes?')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Alerta Stock Mínimo')),
                ('stock_maximo', models.IntegerField(default=1, verbose_name='Alerta Stock Máximo')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo')),
                ('utilidad', models.IntegerField(verbose_name='Utilidad')),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Venta')),
                ('estado_articulo', models.IntegerField(default=1, verbose_name='Estado')),
                ('idcategoriaarticulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categoriaarticulos', verbose_name='Categoría')),
                ('idgiva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.givas', verbose_name='Graba Iva')),
                ('idnivelazucar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articulos.nivelesazucar', verbose_name='Nivel de Azúcar')),
                ('idnivelgrasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articulos.nivelesgrasa', verbose_name='Nivel de Grasa')),
                ('idnivelsal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='articulos.nivelessal', verbose_name='Nivel de Sal')),
                ('idtipoarticulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articulos.tipoarticulos', verbose_name='Tipo Producto')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulos',
                'ordering': ['-estado_articulo', 'descripcion_articulo'],
            },
        ),
    ]
