# Generated by Django 5.1.5 on 2025-05-22 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('proveedores', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompra', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Concepto')),
                ('fecha_compra', models.DateField(verbose_name='Fecha')),
                ('subtotal_tarifa0', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tarifa 0')),
                ('subtotal_tarifa12', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tarifa 15')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('valoriva', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('estado_compra', models.IntegerField(default=1, verbose_name='Estado')),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedores', verbose_name='Proveedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['-idcompra', '-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_compras',
            fields=[
                ('iddetalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Unitario')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('codigoarticulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='articulos.articulos', verbose_name='Artículo')),
                ('idcompra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='compras.compras', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalle Compras',
                'db_table': 'detalle_compras',
            },
        ),
    ]
